Sb/network call
Android-Roadmap/Android-Learning pull request #6
Opened 2023-01-27 11:14 UTC by sb2000sb

Saved-creds login, network call and database implementation done.

2023-01-31 15:48 UTC, Goutam-Kumar requested changes

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/java/com/learning/androidroadmap/Utils.kt
> +//inline fun <V: ViewModel> getViewModelFactory(crossinline getViewModelObject: () -> V):
Please remove this commented code

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/CredsRepo.kt
> +            userDb= UserDatabase.getDatabase(context)
Use koin DI here.

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/CredsRepo.kt
> +            for (i in data.indices){
same here

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/fragments/LoginFragmentNew.kt
> +            if(it == false){
Try to optimize the number of lines here.

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/retrofit/UseRetrofit.kt
> +            .baseUrl("https://jsonplaceholder.typicode.com/")
Don't use the base url string directly. refer it from some constant.

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/retrofit/UseRetrofit.kt
> +    fun getRetrofit(): PlaceHolder {
You may add it in Koin module and whenever you need you may inject in class.

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/viewModels/LoginViewModel.kt
> +class LoginViewModel(val context: Context) : ViewModel() {
Don't use context

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/viewModels/RegistrationViewModel.kt
> +class RegistrationViewModel(val context : Context) : ViewModel() {
Same here too.

2023-01-31 15:48 UTC, Goutam-Kumar commented on app/src/main/res/layout/content_row_layout.xml
> +            android:layout_margin="10dp"
Get it from dimens.xml

2023-01-31 15:48 UTC, Goutam-Kumar commented on build.gradle
> +//buildscript {
please remove these comments.

2023-01-31 15:48 UTC, Goutam-Kumar commented on build.gradle
> +//ext {
here too

2023-02-01 08:32 UTC, sb2000sb commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/databasecomponents/UserEntity.kt
> +data class UserEntity(
Renamed it to PostsData since the information is related to posts

2023-02-02 11:01 UTC, sb2000sb commented on app/src/main/java/com/learning/androidroadmap/mvvmPractice/fragments/LoginFragmentNew.kt
> +            if(it == false){
Code is optimised, but the number of line remained same

2023-02-06 06:30 UTC, Goutam-Kumar approved these changes

2023-02-06 06:30 UTC, merged